import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Sidebar from "@/components/sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const slideWidth = 250;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <Sidebar />
          <div
            className="flex flex-col items-center justify-center min-h-screen bg-gray-100 text-gray-900 font-sans p-2"
            style={{ paddingLeft: `${slideWidth}px` }}
          >
            {children}
          </div>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
